apiVersion: v1
kind: Pod
metadata:
  name: storage-pod-hdd
  namespace: hw46
spec:
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - "echo 'Hello from Yandex Cloud HDD!' > /data/demo.txt && sleep 3600"
    volumeMounts:
    - name: data-vol
      mountPath: /data
  volumes:
  - name: data-vol
    persistentVolumeClaim:
      claimName: my-pvc-hdd
