apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: hw46
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
